# NumPy

In [2]:
import numpy as np

In [3]:
arr1 = np.array([])
arr1

array([], dtype=float64)

In [4]:
my_list=[12,13,14,15]
print(my_list)
print(type(my_list))

[12, 13, 14, 15]
<class 'list'>


In [5]:
a=np.array(my_list)
a

array([12, 13, 14, 15])

In [6]:
type(a)

numpy.ndarray

In [7]:
a.ndim


1

In [8]:
a.size

4

In [9]:
a.shape

(4,)

In [10]:
matrix =  [ [7,86,8],[45,67,87],[65,25,57],[35,67,35]]
matrix

[[7, 86, 8], [45, 67, 87], [65, 25, 57], [35, 67, 35]]

In [11]:
b=np.array(matrix)
b

array([[ 7, 86,  8],
       [45, 67, 87],
       [65, 25, 57],
       [35, 67, 35]])

In [12]:
print("The shape of matrix is",b.shape)

The shape of matrix is (4, 3)


In [13]:
print("The size of matrix is",b.size)

The size of matrix is 12


In [14]:
print("The dimension of matrix is",b.ndim)

The dimension of matrix is 2


In [15]:
print("The type of matrix is",b.dtype)

The type of matrix is int32


In [16]:
arr1=np.array([[[12,23,4],[23,45,65]],[[23,45,56],[32,45,65]]])
arr1

array([[[12, 23,  4],
        [23, 45, 65]],

       [[23, 45, 56],
        [32, 45, 65]]])

In [17]:
arr1.shape

(2, 2, 3)

In [20]:
arr2=arr1.reshape(4,3)

In [21]:
arr2

array([[12, 23,  4],
       [23, 45, 65],
       [23, 45, 56],
       [32, 45, 65]])

In [22]:
np.arange(14)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [28]:
np.arange(300,200,-4)

array([300, 296, 292, 288, 284, 280, 276, 272, 268, 264, 260, 256, 252,
       248, 244, 240, 236, 232, 228, 224, 220, 216, 212, 208, 204])

In [29]:
np.zeros(4)

array([0., 0., 0., 0.])

In [33]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
np.ones((4))

array([1., 1., 1., 1.])

In [35]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
np.ones((3,4,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [39]:
np.linspace(1,15)

array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
        2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
        3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ,
        5.28571429,  5.57142857,  5.85714286,  6.14285714,  6.42857143,
        6.71428571,  7.        ,  7.28571429,  7.57142857,  7.85714286,
        8.14285714,  8.42857143,  8.71428571,  9.        ,  9.28571429,
        9.57142857,  9.85714286, 10.14285714, 10.42857143, 10.71428571,
       11.        , 11.28571429, 11.57142857, 11.85714286, 12.14285714,
       12.42857143, 12.71428571, 13.        , 13.28571429, 13.57142857,
       13.85714286, 14.14285714, 14.42857143, 14.71428571, 15.        ])

In [40]:
np.linspace(2,25,5)

array([ 2.  ,  7.75, 13.5 , 19.25, 25.  ])

In [42]:
np.linspace(1,15,retstep = True)

(array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
         2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
         3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ,
         5.28571429,  5.57142857,  5.85714286,  6.14285714,  6.42857143,
         6.71428571,  7.        ,  7.28571429,  7.57142857,  7.85714286,
         8.14285714,  8.42857143,  8.71428571,  9.        ,  9.28571429,
         9.57142857,  9.85714286, 10.14285714, 10.42857143, 10.71428571,
        11.        , 11.28571429, 11.57142857, 11.85714286, 12.14285714,
        12.42857143, 12.71428571, 13.        , 13.28571429, 13.57142857,
        13.85714286, 14.14285714, 14.42857143, 14.71428571, 15.        ]),
 0.2857142857142857)

In [43]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
a=np.ones((3,4))

In [46]:
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [47]:
a * 4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [48]:
a= a*4-2

In [49]:
a

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [52]:
a.dtype

dtype('float64')

In [53]:
type(a)

numpy.ndarray

In [54]:
arr1=np.arange(20)

In [55]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [56]:
1/arr1

C:\Users\s\AppData\Local\Temp\ipykernel_11984\393800717.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr1


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158])

In [57]:
arr1+arr1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [58]:
arr1*arr1

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361])

In [59]:
arr1/arr1

C:\Users\s\AppData\Local\Temp\ipykernel_11984\1749041114.py:1: RuntimeWarning: invalid value encountered in divide
  arr1/arr1


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [60]:
arr1**arr1

array([          1,           1,           4,          27,         256,
              3125,       46656,      823543,    16777216,   387420489,
        1410065408,  1843829075,  -251658240, -1692154371, -1282129920,
        1500973039,           0,  1681328401,   457441280,  -306639989])

In [68]:
arr2=arr1
arr2

array([30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
       30, 30, 30])

In [69]:
arr2[:1]=30
arr2

array([30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
       30, 30, 30])

In [70]:
arr2[:6]=10

In [71]:
arr2

array([10, 10, 10, 10, 10, 10, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
       30, 30, 30])

In [72]:
arr3=arr2.copy
arr3

<function ndarray.copy>

In [76]:
arr2[8:]=200

In [77]:
arr2

array([ 10,  10,  10,  10,  10,  10,  30,  30, 200, 200, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200])

In [78]:
arr2[4:8]=6

In [79]:
arr2

array([ 10,  10,  10,  10,   6,   6,   6,   6, 200, 200, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200])